service: thumbnail-api
frameworkVersion: '3'
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-iam-roles-per-function
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - '*/*'
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    BUCKET_NAME: thumbnail-api-service-bucket
    REGION: !Ref AWS::Region
    MAX_FILE_SIZE: 11000000
    ORIGINAL_IMAGE_FOLDER: original
    THUMBNAILS_FOLDER: resize
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"

# -----------------------------------------------FUNCTIONS---------------------------------------------------
functions:
  presigned-for-upload:
    handler: src/handlers/presigned-for-upload/handler.main
    events:
      - http:
          method: get
          path: upload-url
  get-thumbnails:
    handler: src/handlers/get-thumbnails/handler.main
    events:
      - http: 
          method: get
          path: download
          request:
            parameters:
              querystrings:
                key: true
  resizer:
    handler: src/handlers/resizer/handler.main
    memorySize: 2048
    timeout: 30
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:*
        Resource: "*"
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: original/

# --------------------------------------------RESOURCES-----------------------------------------------------
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: thumbnail-api-service-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        Tags:
          - Key: Name
            Value: Thumbnail Api Bucket



# --------------------------------------CUSTOM------------------------------------------------------------
custom:
  serverless-offline:
    httpPort: 3000
    payload:
      maxBytes: 30000000

package:
  individually: true
  include: 
    - src/**
    - .env
  exclude:
    - node_modules/**

